#服务访问配置
server:
  port: 8080

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/waimai_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true
    username: root
    password: java
    type: com.alibaba.druid.pool.DruidDataSource

    #druid 配置
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=2000

  #redis配置
  redis:
    host: 127.0.0.1
    #password: xliandong.123
    port: 6379
    jedis:
      pool:
        # 最大连接数（负值表示没有限制）
        max-active: 8
        # 最大阻塞等待时间（负值表示没有限制）
        max-wait: 1
        # 最大空闲链接
        max-idle: 8
        # 最小空闲链接
        min-idle: 0
        # 链接超时时间（毫秒）
        timeout: 36000

  #其他相关配置文件
  profiles:
    active: common #引用sys_common下的yaml文件

  # 上传文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB  #需大于等于最大文件尺寸

#swagger2是否开启
swagger:
  enable: true  #生产环境要关闭

#PageHelper的配置
pagehelper:
  helper-dialect: mysql
  reasonable: false
  default-count: true
